services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=basedb
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
      
volumes:
  mongodb-data:

networks:
  mongodb-network:
    driver: bridge

