services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    # 2022-CU14-ubuntu-22.04
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "S3nh41234567"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql
      
volumes:
  my-volume: